### ISSUE TITLE
8BitDo SNK controller 

### ISSUE THREAD

**Issue by haydnkilyan** [analoguejb/Analogue-Duo-JB#12]
Has a issue pairing - recognises the controller as an FC30 - when it pairs none of the buttons register at all

**Comment by unixchaos** [comment]
I had an issue with this controller not syncing. I used the 2.4 adapter by plugging it in the back and it works great.

**Comment by haydnkilyan** [comment]
Thanks - what firmware are you using on the controller / dongle?

**Comment by haydnkilyan** [comment]
Just tried again - this time just using the button on the side (rather than trying to pair through the controller option in the menu) paired via Bluetooth first time
